name: GTest Sanity Check

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cmake Configure
      run: cmake -B build -DBUILD_TESTING=ON
    - name: Cmake Build
      run: cmake --build build
    - name: Build Ctest
      run: ctest --test-dir build
    - name: Execute Test
      run: cd build && ctest && cd ..
