name: GTest Sanity Check

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cmake
      run: | 
        cmake -B build -DBUILD_TESTING=ON
        cmake --build build
        ctest --test-dir build
        cd build && ctest && cd ..

    - name: Package artifacts
      run: |
          cd build
          tar -czvf odrive-lib.tar.gz libOdrive.a
    
    # Upload release artifact to GitHub Releases
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/odrive-lib.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        